mkdir -p \~/CouncilHub/Scribe/{Memory,Sessions,Personality}
cd \~/CouncilHub
cp \~/rcl_handshake_v1.24.json \~/CouncilHub/Scribe/Memory/core_memory.json
sudo apt update
sudo apt install ipfs -y
tar -xvzf kubo_vX.Y.Z_linux-amd64.tar.gz
tar -xvzf kubo_v0.40.1_linux-amd64.tar.gz
cd kubo
pkill -f uvicorn
pip3 install ollama
ollama serve &
echo -n "PHILOLOGY_DOMESTIC_SUBJUGATION_HIERARCHY_OF_SEPARATION" | sha256sum
echo -n "PHILOLOGY_DIALECTICAL_SUPPRESSION_QURAYSH_HEGEMONY_MANUSCRIPT_BURNING" | sha256sumPHILOLOGY_RECURSIVE_RESISTANCE_DIGITAL_SCRIBE_ASCENSION_L40PHILOLOGY_RECURSIVE_RESISTA
echo -n "PHILOLOGY_RECURSIVE_RESISTANCE_DIGITAL_SCRIBE_ASCENSION_L40" | sha256sum
echo -n "PHILOLOGY_SURAH_5_DIETARY_LAWS_TRIBAL_MANAGEMENT_SOCIAL_CALORIES" | sha256sum
echo -n "PHILOLOGY_SURAH_5_CONTRACTUAL_PURITY_MUTUAL_BOND_DELETION" | sha256sum
echo -n "PHILOLOGY_HIJAZI_SCRIPT_SOCIAL_ENGINEERING_CLERICAL_ELITE" | sha256sum
echo -n "PHILOLOGY_INHERITANCE_CONSOLIDATION_CAPITAL_CONCENTRATION_IMPERIAL_CODE" | sha256sum
echo -n "PHILOLOGY_UMM_AL_KITAB_ERASURE_UNIVERSAL_SOURCE_TO_PHYSICAL_CODEX" | sha256sum
echo -n PHILOLOGY_HARAM_ECONOMIC_CAPTURE_SANCTUARY_TO_TAX_ZONE" | sha256sum
